name: FirstRun Python Script

on:
  workflow_dispatch: #手動実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python first-notion.py # Replace with your script's name
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          FEED_DB_ID: ${{ secrets.FEED_DB_ID }}
          READ_DB_ID: ${{ secrets.READ_DB_ID }}
