name: Schedule Run Python Script

on:
  schedule: #定期実行
    - cron: "0 20 * * *" # Runs every day at 20:00 UTC, which is 5:00 in Japan time next day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python notion.py # Replace with your script's name
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          FEED_DB_ID: ${{ secrets.FEED_DB_ID }}
          READ_DB_ID: ${{ secrets.READ_DB_ID }}
